version: '3.8'

services:
  database:
    image: postgis/postgis:13-master
    platform: linux/amd64
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
      POSTGRES_DB: "directus"
    healthcheck:
      test: ["CMD", "pg_isready", "--host=localhost", "--username=directus"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
    ports:
      - 5432:5432

  cache:
    image: redis:6
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  directus:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: always
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
      - ./templates:/directus/templates
      - ./snapshots:/directus/snapshots
      - ./migrations:/directus/migrations
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    environment:
      LOG_LEVEL: info
      KEY: ${KEY}
      SECRET: ${SECRET}

      DB_CLIENT: pg
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: directus
      DB_USER: directus
      DB_PASSWORD: directus

      CACHE_ENABLED: "true"
      CACHE_AUTO_PURGE: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      STORAGE_LOCATIONS: ${STORAGE_LOCATIONS}
      STORAGE_S3_DRIVER: ${STORAGE_S3_DRIVER}
      STORAGE_S3_KEY: ${STORAGE_S3_KEY}
      STORAGE_S3_SECRET: ${STORAGE_S3_SECRET}
      STORAGE_S3_REGION: ${STORAGE_S3_REGION}
      STORAGE_S3_BUCKET: ${STORAGE_S3_BUCKET}
      STORAGE_S3_ENDPOINT: ${STORAGE_S3_ENDPOINT}

      CORS_ENABLED: ${CORS_ENABLED}
      CORS_ORIGIN: ${CORS_ORIGIN}
      CORS_ALLOWED_HEADERS: ${CORS_ALLOWED_HEADERS}
      CORS_EXPOSED_HEADERS: ${CORS_EXPOSED_HEADERS}
      CORS_METHODS: ${CORS_METHODS}

      EXTENSIONS_PATH: ${EXTENSIONS_PATH}
      EMAIL_TEMPLATES_PATH: ${EMAIL_TEMPLATES_PATH}
      MIGRATIONS_PATH: ${MIGRATIONS_PATH}

      WEBSOCKETS_ENABLED: "true"
      EXTENSIONS_AUTO_RELOAD: "false"